### ISSUE TITLE
No module named "nostr_dvm" when translation dvm tries to respond

### ISSUE THREAD

**Issue by dtdannen** [believethehype/nostrdvm#15]
Ran the current master branch via `python main.py` on a small digital ocean instance, then posted a translation request through vendata.io. This is the error I kept getting:

`Getting profile metadata for npub1mgvwnpsqgrem7jfcwm7pdvdfz2h95mm04r23t8pau2uzxwsdnpgs0gpdjc...
Adding User: da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851 (da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851)
[Google Translator] Received new Request: translation from Dustin Dannenhauer
[Google Translator] Free task or Whitelisted for task translation. Starting processing..
{"id":"f26ba824a7ce3dae071997cb3f7d34aa2157f629ac862545f94596ee5123000d","pubkey":"24851ba52d1d7c090fd92184d9f11caddb760a733b2e9180408c367da7454242","created_at":1704873572,"kind":7000,"tags":[["e","2b9909d6d6628ba84476fe1800c2da81fe98f1fb60b9d747eae4fb8f448612fa"],["alt","NIP90 DVM AI task translation started processing. "],["status","processing"],["p","da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851"]],"content":"NIP90 DVM AI task translation started processing. 👍","sig":"f68f8d6c5defa20892b2f9b13a49e79d6fc3f67a3865c91b5235bfec734f10cc8759a77c5c992be92a3b8d7a73f5aafed1f000669c2986490dbeaf7a8a071e1b"}
{"id":"accf2713a5c818e3dfa8aaae385064b97be3ccd3f2336819efb9dc119e2a553b","pubkey":"ee5595ded47f1c376576cb7d31e786eaf454df24c91ca2d2967062ccf7d28e53","created_at":1704873572,"kind":7000,"tags":[["e","2b9909d6d6628ba84476fe1800c2da81fe98f1fb60b9d747eae4fb8f448612fa"],["alt","NIP90 DVM AI task translation started processing. "],["status","processing"],["p","da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851"]],"content":"NIP90 DVM AI task translation started processing. 👍","sig":"6ba73f38071204bb311562c61f680b2e73c54a19881ffecb78f34ecb2877a03dc6b3b521d04128420057d5adb3412d6ecf1b9c14e4788ccea7439aa05c6eb159"}
[Google Translator]: Sent Kind 7000 Reaction: processing {"id":"accf2713a5c818e3dfa8aaae385064b97be3ccd3f2336819efb9dc119e2a553b","pubkey":"ee5595ded47f1c376576cb7d31e786eaf454df24c91ca2d2967062ccf7d28e53","created_at":1704873572,"kind":7000,"tags":[["e","2b9909d6d6628ba84476fe1800c2da81fe98f1fb60b9d747eae4fb8f448612fa"],["alt","NIP90 DVM AI task translation started processing. "],["status","processing"],["p","da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851"]],"content":"NIP90 DVM AI task translation started processing. 👍","sig":"6ba73f38071204bb311562c61f680b2e73c54a19881ffecb78f34ecb2877a03dc6b3b521d04128420057d5adb3412d6ecf1b9c14e4788ccea7439aa05c6eb159"}
Traceback (most recent call last):
  File "/home/dustin/nostrdvm/nostr_dvm/tasks/translation_google.py", line 3, in <module>
    from nostr_dvm.interfaces.dvmtaskinterface import DVMTaskInterface, process_venv
ModuleNotFoundError: No module named 'nostr_dvm'
Finished processing, loading data..
{"id":"a6faae81e085b72fc56ca9c7206daf0ab6671ced67154fa017a72939c8b49b91","pubkey":"ee5595ded47f1c376576cb7d31e786eaf454df24c91ca2d2967062ccf7d28e53","created_at":1704873572,"kind":7000,"tags":[["e","2b9909d6d6628ba84476fe1800c2da81fe98f1fb60b9d747eae4fb8f448612fa"],["alt","NIP90 DVM AI task translation had an error. "],["status","error"],["p","da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851"]],"content":"NIP90 DVM AI task translation had an error. 👎 ","sig":"98bd539113bcac8eded2de7502a96236163440b79b8ff1fea95bb87aa48eb4947f0e4078c9744fa078eb933f07b5407170ec746871b86a6ccce3e42557ebadeb"}
[Google Translator]: Sent Kind 7000 Reaction: error {"id":"a6faae81e085b72fc56ca9c7206daf0ab6671ced67154fa017a72939c8b49b91","pubkey":"ee5595ded47f1c376576cb7d31e786eaf454df24c91ca2d2967062ccf7d28e53","created_at":1704873572,"kind":7000,"tags":[["e","2b9909d6d6628ba84476fe1800c2da81fe98f1fb60b9d747eae4fb8f448612fa"],["alt","NIP90 DVM AI task translation had an error. "],["status","error"],["p","da18e9860040f3bf493876fc16b1a912ae5a6f6fa8d5159c3de2b8233a0d9851"]],"content":"NIP90 DVM AI task translation had an error. 👎 ","sig":"98bd539113bcac8eded2de7502a96236163440b79b8ff1fea95bb87aa48eb4947f0e4078c9744fa078eb933f07b5407170ec746871b86a6ccce3e42557ebadeb"}
`

nostr_dvm is clearly being imported properly in the beginning when it gets set up. I'm still getting up to speed on the code base. It looks like each dvm may run it's own virtualenv and perhaps the translation virtual_env didn't get nostr_dvm installed?

**Comment by believethehype** [comment]
Hi, by default each dvm is installing it's own venv to avoid dependency conflicts. When the process function runs it uses this venv. 
Did it finish to install dependencies on first run?

A few things you can try for troubleshooting:

In cache/venvs, delete the venv that causes trouble. it will be reinstalled on next start.

If that doesn't fix the problem you can try to go to tasks/translation_google.py and in build_example you can add dvm_config.USE_OWN_VENV = False after line 113. (or copy the code to your main.py and do it there, and call this function instead of the example) You may need to install missing packages in your main venv afterwards.

If you still run into trouble, please let me know.
